[versions]
kotlin = "2.2.21"
ktlint = "1.7.1"
android-tools = "8.13.1"
junit = "5.13.4"
mockito = "6.1.0"
commons-io = "2.21.0"
gradle-publish = "2.0.0"
kotlinter-check = "5.2.0"

[libraries]
ktlint-rule-engine = { group = "com.pinterest.ktlint", name = "ktlint-rule-engine", version.ref = "ktlint" }
ktlint-rule-engine-core = { group = "com.pinterest.ktlint", name = "ktlint-rule-engine-core", version.ref = "ktlint" }
ktlint-cli-reporter-core = { group = "com.pinterest.ktlint", name = "ktlint-cli-reporter-core", version.ref = "ktlint" }
ktlint-cli-reporter-plain = { group = "com.pinterest.ktlint", name = "ktlint-cli-reporter-plain", version.ref = "ktlint" }
ktlint-cli-reporter-html = { group = "com.pinterest.ktlint", name = "ktlint-cli-reporter-html", version.ref = "ktlint" }
ktlint-cli-reporter-checkstyle = { group = "com.pinterest.ktlint", name = "ktlint-cli-reporter-checkstyle", version.ref = "ktlint" }
ktlint-cli-reporter-json = { group = "com.pinterest.ktlint", name = "ktlint-cli-reporter-json", version.ref = "ktlint" }
ktlint-cli-reporter-sarif = { group = "com.pinterest.ktlint", name = "ktlint-cli-reporter-sarif", version.ref = "ktlint" }
ktlint-ruleset-standard = { group = "com.pinterest.ktlint", name = "ktlint-ruleset-standard", version.ref = "ktlint" }
android-tools-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "android-tools" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-jupiter-platform = { group = "org.junit.platform", name= "junit-platform-launcher" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }

[bundles]
ktlint-engine = ["ktlint-rule-engine", "ktlint-rule-engine-core"]
ktlint-reporters = ["ktlint-cli-reporter-core", "ktlint-cli-reporter-plain", "ktlint-cli-reporter-html", "ktlint-cli-reporter-checkstyle", "ktlint-cli-reporter-json", "ktlint-cli-reporter-sarif"]
ktlint-rulesets = ["ktlint-ruleset-standard"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter-check" }
